CREATE TABLE seq_common (
    seq_id VARCHAR(255) PRIMARY KEY,
    seq_count BIGINT
);

CREATE TABLE biz_author_enrichment_job (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_count INTEGER NOT NULL,
    author_uid VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    last_error_code VARCHAR(255),
    last_error_message VARCHAR(2048),
    locked_at TIMESTAMP,
    next_attempt_at TIMESTAMP NOT NULL,
    platform_key VARCHAR(255) NOT NULL,
    priority INTEGER NOT NULL,
    state VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE biz_author_name_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authorprofileid INTEGER,
    displayname VARCHAR(255),
    firstseentime TIMESTAMP,
    lastseentime TIMESTAMP
);

CREATE TABLE biz_author_profile (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authoruid VARCHAR(255), avatar VARCHAR(255), createtime TIMESTAMP,
    displayname VARCHAR(255), homepage VARCHAR(255), platform VARCHAR(255),
    updatetime TIMESTAMP, username VARCHAR(255), signature VARCHAR(1024),
    platformkey VARCHAR(64)
);

CREATE TABLE biz_bili_config (
    id INTEGER PRIMARY KEY,
    bigmember VARCHAR(255), bilicookies VARCHAR(255), bitstream VARCHAR(255),
    cdnsort VARCHAR(255), collectdmm VARCHAR(255), oddmm VARCHAR(255),
    refreshtoken VARCHAR(255)
);

CREATE TABLE biz_blocked_work (
    id INTEGER PRIMARY KEY,
    authorname VARCHAR(255), authoruid VARCHAR(255), createtime TIMESTAMP,
    platform VARCHAR(255), reason VARCHAR(255), sourceurl VARCHAR(255),
    status VARCHAR(255), title VARCHAR(255), updatetime TIMESTAMP,
    workid VARCHAR(255), worktype VARCHAR(255)
);

CREATE TABLE biz_collect_data (
    id INTEGER PRIMARY KEY,
    carriedout VARCHAR(255), count VARCHAR(255), createtime VARCHAR(255),
    endtime VARCHAR(255), generatenfo VARCHAR(255), lastchecktime VARCHAR(255),
    lastid VARCHAR(255), maxcur INTEGER, monitoring VARCHAR(255), omaxcur INTEGER,
    originaladdress VARCHAR(255), platform VARCHAR(255), taskcron VARCHAR(255),
    taskid VARCHAR(255), taskname VARCHAR(255), taskstatus VARCHAR(255),
    taskenabled VARCHAR(255), lastfetchcount INTEGER, lastfetchsnapshot TEXT,
    lastfetchtime VARCHAR(255), lastplanitems TEXT,
    last_seen_publish_time VARCHAR(255), last_seen_work_id VARCHAR(255),
    last_successful_fetch_at TIMESTAMP
);

CREATE TABLE biz_collect_data_detail (
    id INTEGER PRIMARY KEY,
    createtime VARCHAR(255), dataid INTEGER, originaladdress VARCHAR(255),
    status VARCHAR(255), videoid VARCHAR(255), videoname VARCHAR(2000),
    detailjson TEXT, errorcode VARCHAR(255), errormsg VARCHAR(255),
    mediatype VARCHAR(255), processlog TEXT
);

CREATE TABLE biz_collect_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collect_task_id INTEGER NOT NULL, created_at TIMESTAMP NOT NULL,
    error_code VARCHAR(255), error_detail VARCHAR(10000), error_message VARCHAR(2048),
    failed_item_count INTEGER, fetched_count INTEGER, finished_at TIMESTAMP,
    heartbeat_at TIMESTAMP, inserted_count INTEGER, planned_count INTEGER,
    requested_limit INTEGER, skipped_existing_count INTEGER, started_at TIMESTAMP,
    state VARCHAR(255) NOT NULL, trigger_type VARCHAR(255) NOT NULL,
    fetch_stop_reason VARCHAR(64), fetch_warning VARCHAR(255)
);

CREATE TABLE biz_collect_run_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL, event_code VARCHAR(255) NOT NULL,
    level VARCHAR(255) NOT NULL, message VARCHAR(4000) NOT NULL,
    run_id BIGINT NOT NULL, sequence INTEGER NOT NULL, stage VARCHAR(255) NOT NULL,
    work_id VARCHAR(255)
);

CREATE TABLE biz_collect_run_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_uid VARCHAR(255), created_at TIMESTAMP NOT NULL,
    decision VARCHAR(255) NOT NULL, error_code VARCHAR(255),
    error_message VARCHAR(2048), media_type VARCHAR(255),
    nickname_snapshot VARCHAR(255), ordinal INTEGER NOT NULL,
    platform_key VARCHAR(255) NOT NULL, process_state VARCHAR(255) NOT NULL,
    publish_time VARCHAR(255), run_id BIGINT NOT NULL,
    title_snapshot VARCHAR(2000), updated_at TIMESTAMP NOT NULL,
    work_id VARCHAR(255) NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP, error_detail TEXT, finished_at TIMESTAMP,
    locked_at TIMESTAMP, locked_by VARCHAR(255),
    max_attempts INTEGER NOT NULL DEFAULT 4, queue_generation VARCHAR(32),
    started_at TIMESTAMP
);

CREATE TABLE biz_config (
    id INTEGER PRIMARY KEY,
    apptoken VARCHAR(255), ipauth VARCHAR(255), agentaccpass VARCHAR(255),
    agentaddress VARCHAR(255), agentport VARCHAR(255), agenttype VARCHAR(255),
    danmudown VARCHAR(255), filenametemplate VARCHAR(255), frontend VARCHAR(255),
    generatenfo VARCHAR(255), hiddenplatforms VARCHAR(255), nfonetaddr VARCHAR(255),
    openprocesshistory VARCHAR(255), rangenum VARCHAR(255), readonlytoken VARCHAR(255),
    taskcron VARCHAR(255), useragent VARCHAR(255), ytdlpmode VARCHAR(255),
    f2logfullonerror VARCHAR(255), f2logmasksensitive VARCHAR(255),
    f2logmaxpreview VARCHAR(255), mediapreviewlimit VARCHAR(255),
    mediafeedmuted VARCHAR(255), mediahomemode VARCHAR(255), hlsconcurrency VARCHAR(255),
    hlsenable VARCHAR(255), hlsidlewindow VARCHAR(255), hlsmode VARCHAR(255),
    hlsprivacyenabled VARCHAR(255), hlssegmentseconds VARCHAR(255),
    mediafeedsource VARCHAR(255), collectitemintervalms VARCHAR(255),
    collecttaskintervalms VARCHAR(255), douyinapiurls VARCHAR(255),
    graphiclistsortfield VARCHAR(255), graphiclistsortorder VARCHAR(255),
    videolistsortfield VARCHAR(255), videolistsortorder VARCHAR(255)
);

CREATE TABLE biz_cookies_config (
    id INTEGER PRIMARY KEY,
    cookiecloud VARCHAR(255), kuaishoucookie VARCHAR(255), rednotecookie VARCHAR(255),
    twittercookies VARCHAR(255), weibocookie VARCHAR(255), youtubecookies VARCHAR(255),
    kuaishoucookiepool VARCHAR(255), kuaishoucookiestrategy VARCHAR(255)
);

CREATE TABLE biz_database_maintenance_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_size INTEGER NOT NULL, created_at TIMESTAMP NOT NULL,
    current_operation VARCHAR(64), db_fingerprint VARCHAR(80) NOT NULL,
    error_message VARCHAR(2048), estimated_rows BIGINT NOT NULL,
    last_processed_id BIGINT, operations TEXT NOT NULL,
    preview_token_hash VARCHAR(80) NOT NULL UNIQUE,
    processed_rows BIGINT NOT NULL, status VARCHAR(32) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE biz_downloader (
    id INTEGER PRIMARY KEY,
    downloadertype VARCHAR(255), downloaderlink VARCHAR(255), username VARCHAR(255),
    password VARCHAR(255), token VARCHAR(255), downloaderport VARCHAR(255),
    downloadername VARCHAR(255), status VARCHAR(255), downloadpath VARCHAR(255)
);

CREATE TABLE biz_ffmpeg_queue (
    id INTEGER PRIMARY KEY,
    audiostatus VARCHAR(255), createtime VARCHAR(255), filepath VARCHAR(255),
    pendingfolder VARCHAR(255), status VARCHAR(255), videoid VARCHAR(255),
    videoname VARCHAR(255), videostatus VARCHAR(255)
);

CREATE TABLE biz_ffmpeg_queue_data (
    id INTEGER PRIMARY KEY,
    createtime VARCHAR(255), filepath VARCHAR(255), filetype VARCHAR(255),
    queueid INTEGER, status VARCHAR(255), taskid VARCHAR(255)
);

CREATE TABLE biz_graphic_content (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR(255), content TEXT, createtime TIMESTAMP,
    images TEXT, markroute VARCHAR(255), originaladdress VARCHAR(255),
    platform VARCHAR(255), tags VARCHAR(255), title VARCHAR(2000), videoid VARCHAR(255),
    publishtime VARCHAR(255), sourceurl VARCHAR(255), authoravatar VARCHAR(255),
    authoruid VARCHAR(255), authorusername VARCHAR(255), jsondata TEXT,
    secuid VARCHAR(255), uniqueid VARCHAR(255), authorhomepage VARCHAR(512),
    contenttype VARCHAR(32), favorite VARCHAR(32), metadataeditedat TIMESTAMP,
    metadataeditedby VARCHAR(255), metadataoverrides TEXT, platformkey VARCHAR(64),
    privacy VARCHAR(32)
);

CREATE TABLE biz_job_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_count INTEGER NOT NULL, available_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL, dedupe_key VARCHAR(255) NOT NULL,
    job_type VARCHAR(255) NOT NULL, last_error_code VARCHAR(255),
    last_error_message VARCHAR(2048), locked_at TIMESTAMP, locked_by VARCHAR(255),
    max_attempts INTEGER NOT NULL, payload VARCHAR(4000) NOT NULL,
    priority INTEGER NOT NULL, state VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE biz_notify_config (
    id INTEGER PRIMARY KEY,
    dingdingkey VARCHAR(255), dingdingsecret VARCHAR(255), feishukey VARCHAR(255),
    notifychannel VARCHAR(255), qywxkey VARCHAR(255), sctkey VARCHAR(255)
);

CREATE TABLE biz_process_history (
    id INTEGER PRIMARY KEY,
    createtime VARCHAR(255), originaladdress VARCHAR(255), status VARCHAR(255),
    videoplatform VARCHAR(255), tasklog TEXT
);

CREATE TABLE biz_runtime_control (
    control_key VARCHAR(255) PRIMARY KEY,
    enabled INTEGER NOT NULL, reason VARCHAR(1000), updated_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255)
);

CREATE TABLE biz_tiktok_config (
    id INTEGER PRIMARY KEY,
    analysisserver VARCHAR(255), cookies TEXT, cookiepool TEXT,
    cookiestrategy VARCHAR(255), risk_cooldown_minutes INTEGER
);

CREATE TABLE biz_user (
    id INTEGER PRIMARY KEY,
    lasttime VARCHAR(255), password VARCHAR(255), username VARCHAR(255)
);

CREATE TABLE biz_video (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    videoaddr VARCHAR(255), videocover VARCHAR(255), videoname VARCHAR(2000),
    videoplatform VARCHAR(255), createtime TIMESTAMP, videodesc VARCHAR(2000),
    videounrealaddr VARCHAR(255), originaladdress VARCHAR(255),
    videoauthor VARCHAR(255), videoid VARCHAR(255), videoinfo TEXT,
    videoprivacy VARCHAR(255), videotag VARCHAR(255), publishtime VARCHAR(255),
    sourceurl VARCHAR(255), authoravatar VARCHAR(255), authoruid VARCHAR(255),
    authorusername VARCHAR(255), jsondata TEXT, secuid VARCHAR(255),
    uniqueid VARCHAR(255), favorite VARCHAR(255), authorhomepage VARCHAR(512),
    contenttype VARCHAR(32), metadataeditedat TIMESTAMP,
    metadataeditedby VARCHAR(255), metadataoverrides TEXT, platformkey VARCHAR(64)
);

CREATE TABLE biz_video_mix (
    id INTEGER PRIMARY KEY,
    create_time TIMESTAMP, duration INTEGER, mix_name VARCHAR(255) NOT NULL,
    output_path VARCHAR(255), status VARCHAR(255), thumbnail_path VARCHAR(255),
    update_time TIMESTAMP
);

CREATE TABLE biz_video_mix_segment (
    id INTEGER PRIMARY KEY,
    create_time TIMESTAMP, duration INTEGER, end_time INTEGER NOT NULL,
    segment_no INTEGER NOT NULL, start_time INTEGER NOT NULL,
    transition_duration INTEGER, transition_type VARCHAR(255), videoid INTEGER,
    videomixid INTEGER, videoname VARCHAR(255)
);

CREATE INDEX idx_author_enrichment_due ON biz_author_enrichment_job(state, next_attempt_at, priority, id);
CREATE UNIQUE INDEX uq_author_enrichment_active ON biz_author_enrichment_job(platform_key, author_uid)
    WHERE state IN ('QUEUED', 'RUNNING', 'RETRY_WAIT');
CREATE INDEX idx_author_profile_platform_authoruid ON biz_author_profile(platform, authoruid);
CREATE INDEX idx_author_profile_platformkey_authoruid ON biz_author_profile(platformkey, authoruid);
CREATE UNIQUE INDEX uq_collect_run_active_task ON biz_collect_run(collect_task_id)
    WHERE state IN ('QUEUED', 'FETCHING', 'PROCESSING');
CREATE INDEX idx_collect_run_state_heartbeat ON biz_collect_run(state, heartbeat_at);
CREATE INDEX idx_collect_run_task_created ON biz_collect_run(collect_task_id, created_at DESC, id DESC);
CREATE INDEX idx_collect_run_task_id ON biz_collect_run(collect_task_id, id DESC);
CREATE UNIQUE INDEX uq_collect_run_event_sequence ON biz_collect_run_event(run_id, sequence);
CREATE INDEX idx_collect_run_event_run_sequence ON biz_collect_run_event(run_id, sequence);
CREATE INDEX idx_collect_run_item_active_work ON biz_collect_run_item(platform_key, work_id, process_state);
CREATE INDEX idx_collect_run_item_download_claim ON biz_collect_run_item(queue_generation, process_state, available_at, ordinal, created_at, id);
CREATE INDEX idx_collect_run_item_run_ordinal ON biz_collect_run_item(run_id, ordinal);
CREATE INDEX idx_collect_run_item_run_state ON biz_collect_run_item(run_id, process_state);
CREATE INDEX idx_collect_run_item_work ON biz_collect_run_item(run_id, platform_key, work_id);
CREATE UNIQUE INDEX uq_job_queue_active_dedupe ON biz_job_queue(job_type, dedupe_key)
    WHERE state IN ('QUEUED', 'RUNNING', 'RETRY_WAIT');
CREATE INDEX idx_job_queue_claim ON biz_job_queue(state, available_at, priority, id);
CREATE INDEX idx_collect_detail_dataid_mediatype_status ON biz_collect_data_detail(dataid, mediatype, status);
CREATE INDEX idx_collect_detail_dataid_status ON biz_collect_data_detail(dataid, status);
CREATE INDEX idx_collect_detail_dataid_videoid ON biz_collect_data_detail(dataid, videoid);
CREATE INDEX idx_biz_video_author_feed ON biz_video(platformkey, COALESCE(NULLIF(secuid,''), authoruid), publishtime, id);
CREATE INDEX idx_biz_video_author_identity ON biz_video(platformkey, authoruid, secuid);
CREATE INDEX idx_biz_video_createtime_id ON biz_video(createtime, id);
CREATE INDEX idx_biz_video_favorite_id ON biz_video(favorite, id);
CREATE INDEX idx_biz_video_platform_videoid ON biz_video(videoplatform, videoid);
CREATE INDEX idx_biz_video_platformkey_videoid ON biz_video(platformkey, videoid);
CREATE INDEX idx_biz_video_publishtime_id ON biz_video(publishtime, id);
CREATE INDEX idx_biz_video_videoauthor ON biz_video(videoauthor);
CREATE INDEX idx_biz_video_videoid ON biz_video(videoid);
CREATE INDEX idx_biz_video_videoplatform ON biz_video(videoplatform);
CREATE INDEX idx_graphic_content_author ON biz_graphic_content(author);
CREATE INDEX idx_graphic_content_author_feed ON biz_graphic_content(platformkey, COALESCE(NULLIF(secuid,''), authoruid), publishtime, id);
CREATE INDEX idx_graphic_content_author_identity ON biz_graphic_content(platformkey, authoruid, secuid);
CREATE INDEX idx_graphic_content_createtime_id ON biz_graphic_content(createtime, id);
CREATE INDEX idx_graphic_content_platform_videoid ON biz_graphic_content(platform, videoid);
CREATE INDEX idx_graphic_content_platformkey_videoid ON biz_graphic_content(platformkey, videoid);
CREATE INDEX idx_graphic_content_publishtime_id ON biz_graphic_content(publishtime, id);
