DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'biz_collect_data_detail'
          AND column_name = 'id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE biz_collect_data_detail
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

SELECT setval(
    pg_get_serial_sequence('biz_collect_data_detail', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM biz_collect_data_detail), 0), 1),
    EXISTS (SELECT 1 FROM biz_collect_data_detail)
);
