package com.flower.spirit.config;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Properties;

import org.junit.jupiter.api.Test;

class PostgresqlDeploymentContractTest {

    @Test
    void latestImageCanRunMigrationAndSelectDatabaseProfileFromEnvironment() throws Exception {
        String dockerfile = Files.readString(
                Path.of("src", "main", "docker", "buildx", "Dockerfile"), StandardCharsets.UTF_8);

        assertThat(dockerfile)
                .contains("\"psycopg[binary]\"")
                .contains("ENV SPRING_PROFILES_ACTIVE=docker")
                .doesNotContain("--spring.profiles.active=docker");
    }

    @Test
    void postgresqlProfileOverridesSqliteConnectionInitializer() throws Exception {
        Properties docker = new Properties();
        try (var input = Files.newInputStream(
                Path.of("src", "main", "resources", "application-docker.properties"))) {
            docker.load(input);
        }
        Properties postgresql = new Properties();
        try (var input = Files.newInputStream(
                Path.of("src", "main", "resources", "application-postgresql.properties"))) {
            postgresql.load(input);
        }

        String property = "spring.datasource.hikari.connection-init-sql";
        assertThat(docker.getProperty(property)).startsWith("PRAGMA");
        assertThat(postgresql).containsKey(property);
        assertThat(postgresql.getProperty(property)).isEqualTo("SELECT 1");
    }

    @Test
    void longEntityIdentifiersUseBigintIdentityColumns() throws Exception {
        String baseline = Files.readString(Path.of("src", "main", "resources", "db", "migration",
                "postgresql", "V001__baseline.sql"), StandardCharsets.UTF_8);

        for (String table : List.of("biz_collect_run", "biz_collect_run_event", "biz_collect_run_item",
                "biz_database_maintenance_operation", "biz_job_queue")) {
            assertThat(baseline).as(table).contains(
                    "CREATE TABLE " + table + " (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        }
    }
}
