package com.flower.spirit.config;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Properties;

import org.junit.jupiter.api.Test;

class PostgresqlDeploymentContractTest {

    @Test
    void latestImageCanRunMigrationAndSelectDatabaseProfileFromEnvironment() throws Exception {
        String dockerfile = Files.readString(
                Path.of("src", "main", "docker", "buildx", "Dockerfile"), StandardCharsets.UTF_8);

        assertThat(dockerfile)
                .contains("\"psycopg[binary]\"")
                .contains("ENV SPRING_PROFILES_ACTIVE=docker")
                .doesNotContain("--spring.profiles.active=docker");
    }

    @Test
    void postgresqlProfileOverridesSqliteConnectionInitializer() throws Exception {
        Properties docker = new Properties();
        try (var input = Files.newInputStream(
                Path.of("src", "main", "resources", "application-docker.properties"))) {
            docker.load(input);
        }
        Properties postgresql = new Properties();
        try (var input = Files.newInputStream(
                Path.of("src", "main", "resources", "application-postgresql.properties"))) {
            postgresql.load(input);
        }

        String property = "spring.datasource.hikari.connection-init-sql";
        assertThat(docker.getProperty(property)).startsWith("PRAGMA");
        assertThat(postgresql).containsKey(property);
        assertThat(postgresql.getProperty(property)).isEqualTo("SELECT 1");
    }

    @Test
	void longEntityIdentifiersUseBigintIdentityColumns() throws Exception {
		String baseline = Files.readString(Path.of("src", "main", "resources", "db", "migration",
				"postgresql", "V001__baseline.sql"), StandardCharsets.UTF_8);

        for (String table : List.of("biz_collect_run", "biz_collect_run_event", "biz_collect_run_item",
                "biz_database_maintenance_operation", "biz_job_queue")) {
            assertThat(baseline).as(table).contains(
                    "CREATE TABLE " + table + " (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
		}
	}

	@Test
	void integerNativeIdentityEntitiesUseIdentityColumns() throws Exception {
		String baseline = Files.readString(Path.of("src", "main", "resources", "db", "migration",
				"postgresql", "V001__baseline.sql"), StandardCharsets.UTF_8);
		String detailEntity = Files.readString(Path.of("src", "main", "java", "com", "flower", "spirit",
				"entity", "CollectDataDetailEntity.java"), StandardCharsets.UTF_8);

		for (String table : List.of("biz_author_enrichment_job", "biz_author_name_history", "biz_author_profile",
				"biz_graphic_content", "biz_video")) {
			assertThat(baseline).as(table).contains(
					"CREATE TABLE " + table + " (\n    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
		}
		assertThat(baseline).as("biz_collect_data_detail V001 checksum must remain stable")
				.contains("CREATE TABLE biz_collect_data_detail (\n    id INTEGER PRIMARY KEY");
		assertThat(detailEntity)
				.contains("@GeneratedValue(strategy = GenerationType.IDENTITY)")
				.doesNotContain("@TableGenerator");
	}

	@Test
	void collectDetailIdentityMigrationIsSafeForExistingPostgresqlDatabases() throws Exception {
		String migration = Files.readString(Path.of("src", "main", "resources", "db", "migration",
				"postgresql", "V002__collect_detail_identity.sql"), StandardCharsets.UTF_8);

		assertThat(migration)
				.contains("table_name = 'biz_collect_data_detail'")
				.contains("is_identity = 'YES'")
				.contains("ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
				.contains("pg_get_serial_sequence('biz_collect_data_detail', 'id')")
				.contains("SELECT MAX(id) FROM biz_collect_data_detail")
				.contains("EXISTS (SELECT 1 FROM biz_collect_data_detail)");
	}

	@Test
	void mainJavaSqlAvoidsBareNullableParameterChecks() throws Exception {
		StringBuilder sources = new StringBuilder();
		try (var stream = Files.walk(Path.of("src", "main", "java"))) {
			for (Path source : stream.filter(path -> path.toString().endsWith(".java")).toList()) {
				sources.append(Files.readString(source, StandardCharsets.UTF_8)).append('\n');
			}
		}

		assertThat(sources.toString()).doesNotContain("? IS NOT NULL");
	}
}
