FROM ubuntu:22.04

ENV TZ=Asia/Shanghai
ARG BUILD_VERSION=2025.05.12.063524
ENV YT_DLP_VERSION=$BUILD_VERSION

# 设置时区和基础依赖
RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get install -y \
        wget \
        curl \
        openjdk-8-jdk \
        ffmpeg \
        python3 \
        python3-pip \
        python3-venv \
        build-essential \
        python3-dev \
        libffi-dev \
        ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/*

# 创建 Python 虚拟环境并安装 f2
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir f2==0.0.1.7 && \
    /opt/venv/bin/python3 -c "import importlib.metadata; print('f2=' + importlib.metadata.version('f2'))"

# 下载 yt-dlp
RUN wget -O /usr/local/bin/yt-dlp https://github.com/lemon8866/yt-dlp/releases/download/${YT_DLP_VERSION}/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp

ENV YT_DLP_PATH=/usr/local/bin/yt-dlp

VOLUME ["/tmp","/app"]

COPY db /home/app/db/
COPY script /home/app/script/
RUN mkdir -p /app/resources
ADD spirit-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","--spring.profiles.active=docker"]
